name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and run tests with Maven
      run: mvn -B test

    - name: Install doxygen dependencies
      run: sudo apt-get install -y doxygen
    - name: Generate documentation with Doxygen
      run: |
        cd src/main/resources
        doxygen Doxyfile
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/doxygen/html