version: '3.3'

volumes:
    db_data:

services:
    database:
        image: mysql:8.0.25
        container_name: database
        volumes:      
        - db_data:/var/lib/mysql
        - ./mysql-init-files:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jersey
            MYSQL_USER: spq
            MYSQL_PASSWORD: spq 
    server:
        container_name: server
        depends_on:
        - database
        build: .
        ports:
        - "9080:8080"
        restart: always